AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Bucket for SAM deployment artifacts'

Parameters:
  BucketNamePrefix:
    Type: String
    Default: sam-deployment
    Description: Prefix for the S3 bucket name
  
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name

Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketNamePrefix}-${Environment}-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldArtifacts
            Status: Enabled
            ExpirationInDays: 30
            NoncurrentVersionExpirationInDays: 7
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  BucketName:
    Description: Name of the S3 bucket for deployments
    Value: !Ref DeploymentBucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"
  
  BucketArn:
    Description: ARN of the S3 bucket
    Value: !GetAtt DeploymentBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-BucketArn"