name: Deploy SAM Application

on:
  push:
    branches: [ main-deploy ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  BUCKET_NAME:  jota-app-bucket

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Check and Create S3 Bucket
      id: check_bucket
      run: |
        BUCKET_NAME="${{ env.BUCKET_NAME }}"
        REGION="${{ env.AWS_REGION }}"

        if aws s3 ls "s3://${BUCKET_NAME}" --region "$REGION" 2>&1 | gerp -q 'NoBucket'; then
          echo "Creating Bucket ${BUCKET_NAME}..."
          aws s3 mb "s3://${BUCKET_NAME}" --region "$REGION" || exit 1
          echo "Bucket ${BUCKET_NAME} created."
        else
          echo "Bucket already exists."
        fi
      shell: bash 

    - name: Set up SAM CLI
      if: success()
      uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
    
    - name: SAM Build
      if: success()
      run: |
        sam build --template workshop/deploy.yml
    
    - name: SAM Deploy
      if: success()
      run: |
        sam deploy \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --capabilities CAPABILITY_IAM
    
    - name: Show deployment info
      if: success()
      run: |
        echo "✅ Deployment completed successfully!"